name: Contributor License Agreement Policy
description: CLA policy file

resource: repository

configuration: 
   cla:
      content: https://raw.githubusercontent.com/lepoco/.github/main/CLA/lepoco.yml
      minimalChangeRequired: 
         files: 2
         codeLines: 16
      bypassOrgs:
         - lepoco
      bypassUsers:
         - azclibot
         - azure-pipelines[bot]
         - azure-pipelines-bot
         - azure-powershell-bot
         - azuresdkciprbot
         - dependabot[bot]
         - dependabot-preview[bot]
         - dotnet-bot
         - dotnet-corert-bot
         - dotnet-docker-bot
         - dotnet-maestro[bot]
         - dotnet-maestro-bot
         - dotnet-winget-bot

      autoSignMsftEmployee: false

