PR:
  - "*"

dotnet:
  - '**/*.cs'
  
github_actions:
  - ".github/workflows/*"

documentation:
  - "docs/*"

update:
  - "src/Directory.Build.props"

dependencies:
  - "src/Packages.props"
  - "branding/package.json"
  - "src/Packages.props"

NuGet:
  - "src/Packages.props"

styles:
  - "src/Wpf.Ui/**/*.xaml"

themes:
  - "src/Wpf.Ui/Appearance/*"

tray:
  - "src/Wpf.Ui.Tray/*"

controls:
  - "src/Wpf.Ui/Controls/*"

icons:
  - "src/Wpf.Ui/Resources/Fonts/*"

navigation:
  - "src/Wpf.Ui/Controls/NavigationView/*"
